# Generated by Django 6.0.2 on 2026-04-22 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_remove_tutor_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('final_goal', models.CharField(help_text='最終目標', max_length=200)),
                ('final_goal_due', models.DateField(help_text='最終目標の期限')),
                ('overall_advice', models.TextField(blank=True, default='1時間のSNSより、30分の自己学習を！', help_text='全体の意識付け・アドバイス')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='account.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='「1ヶ月後 / By June 20, 2026」など', max_length=50)),
                ('due_date', models.DateField(help_text='目標期限')),
                ('goal_description', models.TextField(help_text='目標の内容')),
                ('self_study_note', models.TextField(blank=True, default='', help_text='自己学習の内容要約')),
                ('advice', models.CharField(choices=[('no_script', '会話のキャッチボールは「感情」を乗せることが鍵。台本を読んでるみたいにならないように！'), ('expose_yourself', '細かいニュアンスはリアルな英語に触れることが大切。常に自分を英語の世界にexposeしていきましょう！'), ('set_alarm', 'リスニングはシャドーイングが鍵！サボらないように、毎日やる時間を決めてコツコツ続けましょう！'), ('starter', '最初は習慣化が難しい、、、。ここで踏ん張って、後の自分に楽をさせてあげましょう！')], default='starter', help_text='講師からのアドバイス', max_length=200)),
                ('order', models.PositiveIntegerField(default=1, help_text='表示順')),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='action_plan.actionplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_important', models.BooleanField(default=False, help_text='「重要」フラグ')),
                ('order', models.PositiveIntegerField(default=1, help_text='表示順')),
                ('action_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_actions', to='action_plan.actionplan')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='action_plan.milestone')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('action_plan', 'order'), name='uq_milestone_order_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_plan__isnull', False), ('milestone__isnull', True)), models.Q(('action_plan__isnull', True), ('milestone__isnull', False)), _connector='OR'), name='ck_action_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(condition=models.Q(('milestone__isnull', True)), fields=('action_plan', 'order'), name='uq_action_order_per_final_goal'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(condition=models.Q(('action_plan__isnull', True)), fields=('milestone', 'order'), name='uq_action_order_per_milestone'),
        ),
    ]
