# Generated by Django 6.0.2 on 2026-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plan', '0002_remove_action_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='label',
            field=models.CharField(help_text='「1ヶ月後」など', max_length=50),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='self_study_note',
            field=models.TextField(blank=True, default='自己学習: シャドーイング、音読、ボキャブラリー（キー動詞、Ultimate Expressions）', help_text='自己学習の内容要約'),
        ),
    ]
