# Generated by Django 6.0.1 on 2026-02-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('base_fee', models.IntegerField(blank=True, null=True)),
                ('special_fee', models.IntegerField(blank=True, null=True)),
                ('final_fee', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('lesson_goal', models.CharField(blank=True, max_length=200)),
                ('hobbies', models.CharField(blank=True, max_length=200)),
                ('referral', models.CharField(blank=True, max_length=200)),
                ('background', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.plan')),
            ],
        ),
    ]
