# Generated by Django 6.0.1 on 2026-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('A0', 'A0'), ('A0~A1', 'A0~A1'), ('A1', 'A1'), ('A1~A2', 'A1~A2'), ('A2', 'A2'), ('A2~B1', 'A2~B1'), ('B1', 'B1'), ('B1~B2', 'B1~B2'), ('B2', 'B2'), ('B2~C1', 'B2~C1'), ('C1', 'C1'), ('C1~C2', 'C1~C2'), ('C2', 'C2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', '振込'), ('credit_card', 'クレカ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', '継続'), ('inactive', '休会'), ('graduated', '卒業'), ('hold', '保留')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='class_rate',
            field=models.IntegerField(blank=True, choices=[(3000, '3,000'), (3300, '3,300')], null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', '振込'), ('Paypal', 'Paypal'), ('other', 'その他')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('active', '在籍'), ('inactive', '休職'), ('resigned', '退職')], max_length=20),
        ),
    ]
