# Generated by Django 6.0.2 on 2026-03-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_student_level_alter_student_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_number',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='tutor_id',
            new_name='tutor_number',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', '振込'), ('paypal', 'Paypal'), ('other', 'その他')], max_length=20),
        ),
    ]
