# Generated by Django 6.0.2 on 2026-04-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_student_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='bank',
        ),
    ]
