# Generated by Django 6.0.1 on 2026-02-12 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_fee_bank', models.IntegerField(blank=True, null=True)),
                ('base_max_weeks', models.IntegerField(blank=True, null=True)),
                ('lessons', models.IntegerField(blank=True, null=True)),
                ('conversation_classes', models.IntegerField(blank=True, null=True)),
                ('ten_talk', models.CharField(blank=True, max_length=50)),
                ('correction_frequency', models.CharField(blank=True, max_length=50)),
                ('base_fee_card', models.IntegerField(blank=True, null=True)),
                ('fee_3m_bank', models.IntegerField(blank=True, null=True)),
                ('fee_3m_card', models.IntegerField(blank=True, null=True)),
                ('fee_6m_bank', models.IntegerField(blank=True, null=True)),
                ('fee_6m_card', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_lesson_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('remaining_lessons', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
