# Generated by Django 6.0.1 on 2026-02-15 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_student_level_alter_student_payment_method_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_lesson_date', models.DateTimeField()),
                ('is_conversation_class', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='booking.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='account.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
