# Generated by Django 6.0.1 on 2026-02-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_fee_bank', models.IntegerField(blank=True, null=True)),
                ('base_max_weeks', models.IntegerField(blank=True, null=True)),
                ('lessons', models.IntegerField(blank=True, null=True)),
                ('conversation_classes', models.IntegerField(blank=True, null=True)),
                ('ten_talk', models.CharField(blank=True, max_length=50)),
                ('correction_frequency', models.CharField(blank=True, max_length=50)),
                ('base_fee_card', models.IntegerField(blank=True, null=True)),
                ('fee_3m_bank', models.IntegerField(blank=True, null=True)),
                ('fee_3m_card', models.IntegerField(blank=True, null=True)),
                ('fee_6m_bank', models.IntegerField(blank=True, null=True)),
                ('fee_6m_card', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
