# Generated by Django 6.0.2 on 2026-03-03 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_student_level_alter_student_payment_method_and_more'),
        ('booking', '0002_lessonstatus_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstatus',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='lessonstatus',
            name='status',
            field=models.CharField(choices=[('reserved', '予約済み'), ('completed', '完了'), ('canceled', 'キャンセル')], default='reserved', max_length=20),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', '振込'), ('credit_card', 'クレカ')], max_length=20)),
                ('lesson_amount', models.IntegerField(blank=True, null=True)),
                ('period_start_date', models.DateField(blank=True, null=True)),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('payment_term_months', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('completed', '終了'), ('ongoing', '受講中'), ('not_consumed', '未消化'), ('suspended', '保留')], default='ongoing', max_length=20)),
                ('is_conversation_class_included', models.BooleanField(default=False)),
                ('receipt_issued', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.plan')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='account.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('zoom_url', models.URLField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ten_talks', to='account.student')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='lessonstatus',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='booking.transaction'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('lesson_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='booking.lessonstatus')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coach', 'start_time'), name='unique_schedule_coach_start_time')],
            },
        ),
        migrations.CreateModel(
            name='TutorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('zoom_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('lesson_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_schedule', to='booking.lessonstatus')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_schedules', to='account.tutor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tutor', 'start_time'), name='unique_tutor_schedule_tutor_start_time')],
            },
        ),
    ]
