# Generated by Django 6.0.2 on 2026-03-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_lessonstatus_is_completed_lessonstatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
