# Generated by Django 6.0.2 on 2026-03-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_term_months',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='plan_name',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
