# Generated by Django 6.0.2 on 2026-03-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_transaction_payment_term_months_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonstatus',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='lessonstatus',
            name='plan',
        ),
    ]
