# Generated by Django 6.0.2 on 2026-03-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_plan_id_and_add_transaction_snapshots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_conversation_class_included',
            new_name='is_conversation_class_completed',
        ),
    ]
